name: No-Ops

on:
  pull_request:
    branches: [main]
    paths:
      - '**'
      - '!app/**'
      - '!*gradle*'

jobs:
  ensure-new-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Only non-source files changed — version bump not required."
  play-store:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Only non-source files changed — play store release not required."